// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASukC6Svzrlx9oKlVX_gb0vVQau3pF8Rg',
    appId: '1:431709216545:web:6dcf39c92b38c7ca2a6860',
    messagingSenderId: '431709216545',
    projectId: 'ageless-welder-367301',
    authDomain: 'ageless-welder-367301.firebaseapp.com',
    storageBucket: 'ageless-welder-367301.appspot.com',
    measurementId: 'G-H3K787L0ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbyiXwYz_qr0bB4lFnpDcRBmfwrssN9U0',
    appId: '1:431709216545:android:f784327c48f45ad32a6860',
    messagingSenderId: '431709216545',
    projectId: 'ageless-welder-367301',
    storageBucket: 'ageless-welder-367301.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeHfnvugGU7mncZgucF8CcivNnq_nW_4I',
    appId: '1:431709216545:ios:525f6bf7966bada02a6860',
    messagingSenderId: '431709216545',
    projectId: 'ageless-welder-367301',
    storageBucket: 'ageless-welder-367301.appspot.com',
    iosClientId: '431709216545-fp9mpu1ok1b8hdd102seuumt8kle3rgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebsse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeHfnvugGU7mncZgucF8CcivNnq_nW_4I',
    appId: '1:431709216545:ios:525f6bf7966bada02a6860',
    messagingSenderId: '431709216545',
    projectId: 'ageless-welder-367301',
    storageBucket: 'ageless-welder-367301.appspot.com',
    iosClientId: '431709216545-fp9mpu1ok1b8hdd102seuumt8kle3rgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebsse',
  );
}
